export const ROLES = {
  ADMIN: 'ADMIN',
  USER: 'USER',
};

export const TASK_STATUS = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
};

export const TASK_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
};

export const ACTIVITY_TYPES = {
  TASK_CREATED: 'TASK_CREATED',
  TASK_UPDATED: 'TASK_UPDATED',
  TASK_DELETED: 'TASK_DELETED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_REGISTERED: 'USER_REGISTERED',
};